---
title: "Using the waggle dance to quantify collective foraging: speech"
author: "Joe Palmer, Ash Samuelson, Elli Leadbeater & Vincent Jansen"
date: "8/11/2021"
output:
  word_document
bibliography: paper-refs.bib
---


# Slide 1 (background)

Collective foraging occurs when individuals interact in a way which allows decisions to be made collectively rather than individually. In honeybee foraging, individuals use the waggle dance to direct others to profitable resources. When a forager finds a profitable flower patch they will return to the hive and dance in proportion to how good they assess that patch to be, so more profitable patches elicit more dances. Other foragers wander around the dance floor randomly and will follow the first dance they find and so, at the collective level, recruitment occurs in proportion to resource quality. Individuals follow a dance and then report their own assessment of the resource in the number of dances they perform when they return to the hive. This creates a feedback mechanism through which the hive processes the information collected by individuals and proportionally selects the most profitable resources.

# Slide 2 (problem/gap)

Despite the complexity of this behaviour, a collective strategy is not always the most profitable option. In some circumstances, you are better off priorotising information you gather yourself (personal information) than using information provided by others (social information). It is now generally accepted that in many cases collective foraging is flexibly adopted in response to the environment, however, evaluating how the environment influences collective foraging requires quantifying the degree to which animal groups make collective decisions. To do this you need to compare the actions and decision making of a collective with that of individual actors. This is fundamentally difficult as in most cases we can observe an individual, or a collective, but not both.

# Slide 3 (objective to fill gap)

What I am going to show you today is a model of honeybee foraging that can be used to distinguish collective from individual decision making. We confronted this model with waggle dance data from twenty hives, collected across two years in an urban and agri-rural environment, to infer to what extent each colonies foraging depends on collective vs individual decision-making. From fitting this model we obtain a metric describing the use of the waggle dance, providing us with an important tool for probing how the environment influences the use of individual and socially derived information.

# Slide 4 (Simulation / sanity check)

Because individuals report where they’ve been on the dance floor, we hypothesised that the type of foraging strategy, either using personal or social information, would influence the patterns of dances reported. To test this idea we built a simulation of honeybee foraging and examined the distribution of dances reported by foragers acting on individual vs social information.

# slide 5 (simulation plot)

[Simulation plot]

These two garden looking plots show how foraging works in the simulation using individual and social information. In the left plot individuals leave the hive on a random flight path, shown by the white lines and continue until they encounter a flower. In this right plot, some individuals continue to forage using their own personal information, again following the white lines, but recruits sample available dances provided by others and so get biased towards better resources. The graphs here show the Log inverse frequency distribution, which is just the log probability of sampling a distance greater than x,  of foraging distances reported under the two strategies. This top plot shows just individual information use and  looks visibly different to the bottom one where we have recruitment. This result confirms our assumption. The shape of the distance distribution carries information about the extent to which honeybee colonies collectively make foraging decisions.

# Slide 6 (Introduce model)

By incorporating the theoretical narrative of honeybee foraging with what we have learned from our simulation about dance distributions under different foraging strategies, we produced a foraging model which identifies the proportion of dances that follow an individual or social information use distribution and compared this to actual waggle dance data to see how real colonies use collective and social information when foraging.

# Slide 7 (model results overall)

[Model results]

This map shows the location of the hives as points which are colored and shaped by the model which fit best in those sites. In 17 out of the 20 sites the collective model provided a better explanation of the data, as shown by the black circles. In three of the sites though, the data was better explained by a strategy of foragers working on only personal information and ignoring the dance, these are shown by the red triangles. Now these results compare the two models but we need a goodness of fit statistic in order to see if the explanation of the data fits well. Figure B. shows the distribution of KS statistic P values across the sites for each model fit. Here, a p value greater than 0.05 means there is no statistically significant difference between our model and the data. In 17 of the 20 sites, the collective model fit is not statistically different from the underlying data, whereas in the individual model 9 sites show a significant difference between the data and the individual model fit. This indicates that in the majority of sites both models provide a very good explanation of the data.

# Slide 8 (model results site fits)

These two plots here show the model fit to the data for sites STU (left) and ZSL (right) where the individual and collective models provided the better fit respectively. Again the axis here is log probability of observing a value greater than or equal to x and so we can see there is a very, very close fit to the data.

# Slide 9 (model fit conclusion, next steps)

So, in fitting our model we have shown that in the majority of cases honeybee colonies forage collectively using the waggle dance. No surprise there, however, in some sites the data can be explained just as well by a strategy of ignoring the waggle dance and relying on personal information. These results support theoretical ideas that the environment influences the value of social and personal information. Prior to this study, some empirical work has shown individuals do better without the dance in certain landscapes, but they have not been able to quantify the extent to which the dance is used. Our model indicates the proportion of dances coming from either an individual or social information use strategy and so provides a method to do just that. This also allows us to probe how the environment influences information use in more detail.

# Slide 10 (Introduce land use)

In addition to waggle dance data for each site, we also catergorised the different land-use types which made up each sites local environment. We then performed a Partial Least Squares analysis to find the main axis of land-use type which best explains the variation in the proportion of dances coming from an individual strategy, which I term here as proportion of scout dances.

# Slide 11 (Agri-rural land-use results)

In the agri-rural environment we identify a single PC explains around 60% of the variation in the proportion of scout dances and shows a significant positive correlation. This PC correlates positively with arable land and negatively with non-agricultural unmanaged green space, built up areas and water. Arable land is typically nutritionally poor for honeybees (ref). On the contrary, non-agricultural unmanaged green space is typically nutrient rich, as are built up areas in agri-rural environments, which often have gardens with ample flowers available (ref). Water also correlates negatively with the estimated proportion of scouts, possibly due to river and pond banks providing good floral resources for pollinators (ref). Combined, these results suggests when resources are sparse and difficult to find, as with arable land-use, individuals value personal information more than when easier to find, which is what you’d expect with the non-agricultural unmanaged green space, built up areas and water.

# slide 12 (Urban land-use results)

We find a similar story in the urban environment, where a single PC explains approximately 61% of the variance in the proportion of scouts and again shows a significant positive correlation. This PC correlates positively with continuous central land, dense residential land and water, whilst correlating negatively with sparse residential and amenity grassland. This relationship appears to be largely driven by a single site showing a model of only individual foraging as the best fit. Nevertheless, as with the agri-rural land-uses, these results indicate when resources are sparse, as could be expected in continuous central and dense residential land, where there is limited space for floral resources, a colony emphasises the use of personal rather than social information. When resources are more abundant though, as could be expected in sparse residential areas and amenity grasslands, a colony appears to increase the use of the waggle dance. Unlike in the agri-rural environment, water correlates positively with a higher use of the waggle dance, which suggests that the banks of urban water ways are less nutritionally rich than in agri-rural landscapes.

# Slide 13 (Land-use conclusion)

These results demonstrate how our methodology can be used to investigate how environmental factors influence the use of the waggle dance. Although we have limited data on this, our findings nevertheless provide an insight into how human land-use change through urbanisation and agricultural intensification is influencing how honeybees use the waggle dance. Interestingly, these results indicate that human activity is selecting honeybees to ignore social information in favor of individual information.

# Slide 14 (Overall conclusion)

Overall, we have demonstrated that the analysis of waggle dance data can make an important contribution to our understanding of social information use. With recent advances in automatic waggle dance decoding, we face the prospect of waggle dance data becoming “big data”. Our methodology provides a means of analysing such large data sets and gleaning useful information to inform the debate about the importance of social and personal information, as well as providing useful colony metrics of foraging activity.

# Slide 15 (Finish)

Thank you all for listening. If you have any questions please feel free to approach me after the talk.
