---
title: "Waggle dance distributions quantify collective foraging in honey bee colonies: Supplementary material"
author: "Joseph Palmer, Ash Samuelson, Elli Leadbeater and Vincent Jansen"
output:
  word_document
always_allow_html: true
bibliography: paper-refs.bib
# csl: nature.csl
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
library(showtext)
showtext_auto()

knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "man/figures/README-",
  out.width = "100%"
)
library(ggplot2)
library(cowplot)
theme_set(
  theme_classic() +
    theme(
      text = element_text(size = 18)
    )
)

library(dplyr)
library(kableExtra)
library(flextable)
library(tibble)
library(purrr)

# load fitting results / stats
load("results/site_fit_results.Rdata")
```


# Waggle dance model

# Waggle dance model fit

Fig 1. shows the models fit to all 20 sites.

```{r, all-model-fits}

plots <- map(all_sites, 2)
plots <- plots %>%
  map(
    ~ {.x + theme(
      axis.title.x = element_blank(),
      axis.title.y = element_blank()
    )}
  )
print(plots$BEL)

plot_grid(plotlist = plots, nrow = 5)

```

Table 1. shows the results of the model fitting, including likelihood scores, parsimony measures -AIC, delta_AIC, rAIC (relative delta_AIC) and wAIC (Akaike weights)- and goodness of fit -Ks statistics (ks_statistic, ks_pvalue)- for all 20 sites.

```{r, model-fit-results}
set_flextable_defaults(
  big.mark = " ",
  font.size = 10, theme_fun = theme_vanilla,
  padding.bottom = 6,
  padding.top = 6,
  padding.left = 6,
  padding.right = 6
)

# load fit data
load("results/site_fit_results.Rdata")

# group all site results together
df <- map(all_sites, 1) %>%
  bind_rows()

# calculate other AIC stats
df2 <- df %>%
  group_by(site) %>%
  mutate(
    delta_AIC = AIC - min(AIC),
    rAIC = exp(-0.5 * delta_AIC),
    wAIC = rAIC / sum(rAIC)
  ) %>%
  select(
    site, model, loglikelihood, AIC, delta_AIC, rAIC, wAIC,
    p, bs, br, as, ar, k, ks_statistic, ks_pvalue
  )

# format table
df2 %>%
  arrange(site) %>%
  mutate(across(where(is.numeric), round, 3)) %>%
  flextable() %>%
  set_caption(
    "Fit results for the fitting of the waggle dance model to each site."
  ) %>%
  set_table_properties(layout = "autofit")
```
