---
output: github_document
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "man/figures/README-",
  out.width = "100%"
)
```

# Honey bees vary collective decision making in different landscapes

---

This directory contains all the code and data needed to reproduce the article:

(insert article reference)

# Instructions

---

The manuscript is an R-markdown document called `paper.Rmd`. This is rendered into a word document called `paper.doc`. The Supplementary material is a tex file, `supplementary_material.tex`.

All generic code to fit the models is defined in the `wagglefit` package whilst specific code is stored in the `Code` directory. The simulation code is written in python and and can be found in `Code/Simulation`.

`agent_based_sim.Rmd` contains code use to make the simulation plots. These results are stored in `Simulation/Results` and were used to create figures 2 and 3 in an external editing program.
`fit_data.R` contains functions to fit the models to the data used in this study (these functions are called in the r-markdown files).
`fit_models_durations.Rmd` contains code to fit the models to the duration of waggle dance runs. The results are stored in `Results/figures` and used to create figures 4 and 5 in an external editing program.
`landuse_effect_jackknife.Rmd` contains code to run the jackknifed PLS analysis. Results are stored in the `Results/figures` directory and used to create figure 5 in an external editing program.
`supplementary_material.Rmd` contains code to create the supplementary figures and tables included in the supplementary material.

Running these analyses creates the raw figures which are then combined in editing software to produce the manuscript figures used in the publication. The final figures can be found in `Results/figures/manuscript_figures/`

You can then recreate the manuscript by kitting the paper.Rmd file.
