// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// alter_in_place
void alter_in_place(NumericVector x);
RcppExport SEXP _wagglefit_alter_in_place(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    alter_in_place(x);
    return R_NilValue;
END_RCPP
}
// scout_dist
double scout_dist(double x, double m, double p, double ls, double qn, double a);
RcppExport SEXP _wagglefit_scout_dist(SEXP xSEXP, SEXP mSEXP, SEXP pSEXP, SEXP lsSEXP, SEXP qnSEXP, SEXP aSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type x(xSEXP);
    Rcpp::traits::input_parameter< double >::type m(mSEXP);
    Rcpp::traits::input_parameter< double >::type p(pSEXP);
    Rcpp::traits::input_parameter< double >::type ls(lsSEXP);
    Rcpp::traits::input_parameter< double >::type qn(qnSEXP);
    Rcpp::traits::input_parameter< double >::type a(aSEXP);
    rcpp_result_gen = Rcpp::wrap(scout_dist(x, m, p, ls, qn, a));
    return rcpp_result_gen;
END_RCPP
}
// recruit_dist
double recruit_dist(double x, double m, double p, double ln, double qn, double a);
RcppExport SEXP _wagglefit_recruit_dist(SEXP xSEXP, SEXP mSEXP, SEXP pSEXP, SEXP lnSEXP, SEXP qnSEXP, SEXP aSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type x(xSEXP);
    Rcpp::traits::input_parameter< double >::type m(mSEXP);
    Rcpp::traits::input_parameter< double >::type p(pSEXP);
    Rcpp::traits::input_parameter< double >::type ln(lnSEXP);
    Rcpp::traits::input_parameter< double >::type qn(qnSEXP);
    Rcpp::traits::input_parameter< double >::type a(aSEXP);
    rcpp_result_gen = Rcpp::wrap(recruit_dist(x, m, p, ln, qn, a));
    return rcpp_result_gen;
END_RCPP
}
// loglike_model_all
double loglike_model_all(NumericVector x, double p, double ls, double ln, double qn, double a);
RcppExport SEXP _wagglefit_loglike_model_all(SEXP xSEXP, SEXP pSEXP, SEXP lsSEXP, SEXP lnSEXP, SEXP qnSEXP, SEXP aSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< double >::type p(pSEXP);
    Rcpp::traits::input_parameter< double >::type ls(lsSEXP);
    Rcpp::traits::input_parameter< double >::type ln(lnSEXP);
    Rcpp::traits::input_parameter< double >::type qn(qnSEXP);
    Rcpp::traits::input_parameter< double >::type a(aSEXP);
    rcpp_result_gen = Rcpp::wrap(loglike_model_all(x, p, ls, ln, qn, a));
    return rcpp_result_gen;
END_RCPP
}
// loglike_model_scout
double loglike_model_scout(NumericVector x, double ls, double qn, double a);
RcppExport SEXP _wagglefit_loglike_model_scout(SEXP xSEXP, SEXP lsSEXP, SEXP qnSEXP, SEXP aSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< double >::type ls(lsSEXP);
    Rcpp::traits::input_parameter< double >::type qn(qnSEXP);
    Rcpp::traits::input_parameter< double >::type a(aSEXP);
    rcpp_result_gen = Rcpp::wrap(loglike_model_scout(x, ls, qn, a));
    return rcpp_result_gen;
END_RCPP
}
// loglike_model_recruit
double loglike_model_recruit(NumericVector x, double ln, double qn, double a);
RcppExport SEXP _wagglefit_loglike_model_recruit(SEXP xSEXP, SEXP lnSEXP, SEXP qnSEXP, SEXP aSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< double >::type ln(lnSEXP);
    Rcpp::traits::input_parameter< double >::type qn(qnSEXP);
    Rcpp::traits::input_parameter< double >::type a(aSEXP);
    rcpp_result_gen = Rcpp::wrap(loglike_model_recruit(x, ln, qn, a));
    return rcpp_result_gen;
END_RCPP
}
// optimise_all
NumericVector optimise_all(NumericVector x, NumericVector params, NumericVector lb, NumericVector ub);
RcppExport SEXP _wagglefit_optimise_all(SEXP xSEXP, SEXP paramsSEXP, SEXP lbSEXP, SEXP ubSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type params(paramsSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type lb(lbSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type ub(ubSEXP);
    rcpp_result_gen = Rcpp::wrap(optimise_all(x, params, lb, ub));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_wagglefit_alter_in_place", (DL_FUNC) &_wagglefit_alter_in_place, 1},
    {"_wagglefit_scout_dist", (DL_FUNC) &_wagglefit_scout_dist, 6},
    {"_wagglefit_recruit_dist", (DL_FUNC) &_wagglefit_recruit_dist, 6},
    {"_wagglefit_loglike_model_all", (DL_FUNC) &_wagglefit_loglike_model_all, 6},
    {"_wagglefit_loglike_model_scout", (DL_FUNC) &_wagglefit_loglike_model_scout, 4},
    {"_wagglefit_loglike_model_recruit", (DL_FUNC) &_wagglefit_loglike_model_recruit, 4},
    {"_wagglefit_optimise_all", (DL_FUNC) &_wagglefit_optimise_all, 4},
    {NULL, NULL, 0}
};

RcppExport void R_init_wagglefit(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
