// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// alter_in_place
void alter_in_place(NumericVector x);
RcppExport SEXP _wagglefit_alter_in_place(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    alter_in_place(x);
    return R_NilValue;
END_RCPP
}
// heaviside
double heaviside(double x);
RcppExport SEXP _wagglefit_heaviside(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(heaviside(x));
    return rcpp_result_gen;
END_RCPP
}
// scout_ccdf
double scout_ccdf(double x, double p, double ls, double qn, double a, double m);
RcppExport SEXP _wagglefit_scout_ccdf(SEXP xSEXP, SEXP pSEXP, SEXP lsSEXP, SEXP qnSEXP, SEXP aSEXP, SEXP mSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type x(xSEXP);
    Rcpp::traits::input_parameter< double >::type p(pSEXP);
    Rcpp::traits::input_parameter< double >::type ls(lsSEXP);
    Rcpp::traits::input_parameter< double >::type qn(qnSEXP);
    Rcpp::traits::input_parameter< double >::type a(aSEXP);
    Rcpp::traits::input_parameter< double >::type m(mSEXP);
    rcpp_result_gen = Rcpp::wrap(scout_ccdf(x, p, ls, qn, a, m));
    return rcpp_result_gen;
END_RCPP
}
// recruit_ccdf
double recruit_ccdf(double x, double p, double ln, double qn, double a, double m);
RcppExport SEXP _wagglefit_recruit_ccdf(SEXP xSEXP, SEXP pSEXP, SEXP lnSEXP, SEXP qnSEXP, SEXP aSEXP, SEXP mSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type x(xSEXP);
    Rcpp::traits::input_parameter< double >::type p(pSEXP);
    Rcpp::traits::input_parameter< double >::type ln(lnSEXP);
    Rcpp::traits::input_parameter< double >::type qn(qnSEXP);
    Rcpp::traits::input_parameter< double >::type a(aSEXP);
    Rcpp::traits::input_parameter< double >::type m(mSEXP);
    rcpp_result_gen = Rcpp::wrap(recruit_ccdf(x, p, ln, qn, a, m));
    return rcpp_result_gen;
END_RCPP
}
// ccdf_model_all
void ccdf_model_all(NumericVector x, NumericVector y, double p, double ls, double ln, double qn, double a);
RcppExport SEXP _wagglefit_ccdf_model_all(SEXP xSEXP, SEXP ySEXP, SEXP pSEXP, SEXP lsSEXP, SEXP lnSEXP, SEXP qnSEXP, SEXP aSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type y(ySEXP);
    Rcpp::traits::input_parameter< double >::type p(pSEXP);
    Rcpp::traits::input_parameter< double >::type ls(lsSEXP);
    Rcpp::traits::input_parameter< double >::type ln(lnSEXP);
    Rcpp::traits::input_parameter< double >::type qn(qnSEXP);
    Rcpp::traits::input_parameter< double >::type a(aSEXP);
    ccdf_model_all(x, y, p, ls, ln, qn, a);
    return R_NilValue;
END_RCPP
}
// ccdf_model_scout
void ccdf_model_scout(NumericVector x, NumericVector y, double ls, double qn, double a);
RcppExport SEXP _wagglefit_ccdf_model_scout(SEXP xSEXP, SEXP ySEXP, SEXP lsSEXP, SEXP qnSEXP, SEXP aSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type y(ySEXP);
    Rcpp::traits::input_parameter< double >::type ls(lsSEXP);
    Rcpp::traits::input_parameter< double >::type qn(qnSEXP);
    Rcpp::traits::input_parameter< double >::type a(aSEXP);
    ccdf_model_scout(x, y, ls, qn, a);
    return R_NilValue;
END_RCPP
}
// ccdf_model_recruit
void ccdf_model_recruit(NumericVector x, NumericVector y, double ln, double qn, double a);
RcppExport SEXP _wagglefit_ccdf_model_recruit(SEXP xSEXP, SEXP ySEXP, SEXP lnSEXP, SEXP qnSEXP, SEXP aSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type y(ySEXP);
    Rcpp::traits::input_parameter< double >::type ln(lnSEXP);
    Rcpp::traits::input_parameter< double >::type qn(qnSEXP);
    Rcpp::traits::input_parameter< double >::type a(aSEXP);
    ccdf_model_recruit(x, y, ln, qn, a);
    return R_NilValue;
END_RCPP
}
// model_ccdf
NumericVector model_ccdf(NumericVector x, NumericVector params, int model);
RcppExport SEXP _wagglefit_model_ccdf(SEXP xSEXP, SEXP paramsSEXP, SEXP modelSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type params(paramsSEXP);
    Rcpp::traits::input_parameter< int >::type model(modelSEXP);
    rcpp_result_gen = Rcpp::wrap(model_ccdf(x, params, model));
    return rcpp_result_gen;
END_RCPP
}
// scout_dist
double scout_dist(double x, double m, double p, double ls, double qn, double a);
RcppExport SEXP _wagglefit_scout_dist(SEXP xSEXP, SEXP mSEXP, SEXP pSEXP, SEXP lsSEXP, SEXP qnSEXP, SEXP aSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type x(xSEXP);
    Rcpp::traits::input_parameter< double >::type m(mSEXP);
    Rcpp::traits::input_parameter< double >::type p(pSEXP);
    Rcpp::traits::input_parameter< double >::type ls(lsSEXP);
    Rcpp::traits::input_parameter< double >::type qn(qnSEXP);
    Rcpp::traits::input_parameter< double >::type a(aSEXP);
    rcpp_result_gen = Rcpp::wrap(scout_dist(x, m, p, ls, qn, a));
    return rcpp_result_gen;
END_RCPP
}
// recruit_dist
double recruit_dist(double x, double m, double p, double ln, double qn, double a);
RcppExport SEXP _wagglefit_recruit_dist(SEXP xSEXP, SEXP mSEXP, SEXP pSEXP, SEXP lnSEXP, SEXP qnSEXP, SEXP aSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type x(xSEXP);
    Rcpp::traits::input_parameter< double >::type m(mSEXP);
    Rcpp::traits::input_parameter< double >::type p(pSEXP);
    Rcpp::traits::input_parameter< double >::type ln(lnSEXP);
    Rcpp::traits::input_parameter< double >::type qn(qnSEXP);
    Rcpp::traits::input_parameter< double >::type a(aSEXP);
    rcpp_result_gen = Rcpp::wrap(recruit_dist(x, m, p, ln, qn, a));
    return rcpp_result_gen;
END_RCPP
}
// loglike_model_all
double loglike_model_all(NumericVector x, double p, double ls, double ln, double qn, double a);
RcppExport SEXP _wagglefit_loglike_model_all(SEXP xSEXP, SEXP pSEXP, SEXP lsSEXP, SEXP lnSEXP, SEXP qnSEXP, SEXP aSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< double >::type p(pSEXP);
    Rcpp::traits::input_parameter< double >::type ls(lsSEXP);
    Rcpp::traits::input_parameter< double >::type ln(lnSEXP);
    Rcpp::traits::input_parameter< double >::type qn(qnSEXP);
    Rcpp::traits::input_parameter< double >::type a(aSEXP);
    rcpp_result_gen = Rcpp::wrap(loglike_model_all(x, p, ls, ln, qn, a));
    return rcpp_result_gen;
END_RCPP
}
// loglike_model_scout
double loglike_model_scout(NumericVector x, double ls, double qn, double a);
RcppExport SEXP _wagglefit_loglike_model_scout(SEXP xSEXP, SEXP lsSEXP, SEXP qnSEXP, SEXP aSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< double >::type ls(lsSEXP);
    Rcpp::traits::input_parameter< double >::type qn(qnSEXP);
    Rcpp::traits::input_parameter< double >::type a(aSEXP);
    rcpp_result_gen = Rcpp::wrap(loglike_model_scout(x, ls, qn, a));
    return rcpp_result_gen;
END_RCPP
}
// loglike_model_recruit
double loglike_model_recruit(NumericVector x, double ln, double qn, double a);
RcppExport SEXP _wagglefit_loglike_model_recruit(SEXP xSEXP, SEXP lnSEXP, SEXP qnSEXP, SEXP aSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< double >::type ln(lnSEXP);
    Rcpp::traits::input_parameter< double >::type qn(qnSEXP);
    Rcpp::traits::input_parameter< double >::type a(aSEXP);
    rcpp_result_gen = Rcpp::wrap(loglike_model_recruit(x, ln, qn, a));
    return rcpp_result_gen;
END_RCPP
}
// optimise_model
NumericVector optimise_model(NumericVector x, NumericVector params, NumericVector lb, NumericVector ub, bool verbose, double xtol, int model);
RcppExport SEXP _wagglefit_optimise_model(SEXP xSEXP, SEXP paramsSEXP, SEXP lbSEXP, SEXP ubSEXP, SEXP verboseSEXP, SEXP xtolSEXP, SEXP modelSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type params(paramsSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type lb(lbSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type ub(ubSEXP);
    Rcpp::traits::input_parameter< bool >::type verbose(verboseSEXP);
    Rcpp::traits::input_parameter< double >::type xtol(xtolSEXP);
    Rcpp::traits::input_parameter< int >::type model(modelSEXP);
    rcpp_result_gen = Rcpp::wrap(optimise_model(x, params, lb, ub, verbose, xtol, model));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_wagglefit_alter_in_place", (DL_FUNC) &_wagglefit_alter_in_place, 1},
    {"_wagglefit_heaviside", (DL_FUNC) &_wagglefit_heaviside, 1},
    {"_wagglefit_scout_ccdf", (DL_FUNC) &_wagglefit_scout_ccdf, 6},
    {"_wagglefit_recruit_ccdf", (DL_FUNC) &_wagglefit_recruit_ccdf, 6},
    {"_wagglefit_ccdf_model_all", (DL_FUNC) &_wagglefit_ccdf_model_all, 7},
    {"_wagglefit_ccdf_model_scout", (DL_FUNC) &_wagglefit_ccdf_model_scout, 5},
    {"_wagglefit_ccdf_model_recruit", (DL_FUNC) &_wagglefit_ccdf_model_recruit, 5},
    {"_wagglefit_model_ccdf", (DL_FUNC) &_wagglefit_model_ccdf, 3},
    {"_wagglefit_scout_dist", (DL_FUNC) &_wagglefit_scout_dist, 6},
    {"_wagglefit_recruit_dist", (DL_FUNC) &_wagglefit_recruit_dist, 6},
    {"_wagglefit_loglike_model_all", (DL_FUNC) &_wagglefit_loglike_model_all, 6},
    {"_wagglefit_loglike_model_scout", (DL_FUNC) &_wagglefit_loglike_model_scout, 4},
    {"_wagglefit_loglike_model_recruit", (DL_FUNC) &_wagglefit_loglike_model_recruit, 4},
    {"_wagglefit_optimise_model", (DL_FUNC) &_wagglefit_optimise_model, 7},
    {NULL, NULL, 0}
};

RcppExport void R_init_wagglefit(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
