# Honeybee foraging analysis
## Joseph Palmer
---

### Synopsis

This document contains the analysis of models fit to the data using `run_all_models()`

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "man/figures/README-",
  out.width = "100%"
)
library(ggplot2)
theme_set(
  theme_classic() +
    theme(
      text = element_text(family = "URWHelvetica", size = 8)
    )
)
library(cowplot)
library(dplyr)
library(tibble)
source("analysis/fit_data.R")
```


```{r}

path <- "analysis/results_version1"
data <- get_data()

sites <- purrr::map_chr(
  list.files(path),
  ~ {
    return(gsub(".rds", "", .x))
  }
)

plots_data <- purrr::map(
  sites,
  ~ {
    subdat <- data %>% dplyr::filter(.data$site == .x)
    df <- readRDS(paste0(path, "/", .x, ".rds"))[-3]
    results_tibble <- make_results_tibble(df) %>%
      rowwise() %>%
      mutate(
        ks_p = calc_ks_boot(
          subdat$foraging_distance, c(p, ls, ln, qn, a),
          data_name, TRUE
        ),
        ks_d = calc_ks(
          subdat$foraging_distance, c(p, ls, ln, qn, a),
          data_name, TRUE
        ),
        site = .x
      ) %>%
      select(
        site,
        everything()
      )
    print(paste(.x, length(subdat$foraging_distance)))
    if (.x == "STU") {
      ret <- list(
        site_name = list(
          results_tibble,
          make_full_plot(
            subdat$foraging_distance, df,
            subplot_coords = c(0.5, 6, -6, -2.5)
          )
        )
      )
    } else if (.x == "CAD") {
      ret <- list(
        site_name = list(
          results_tibble,
          make_full_plot(
            subdat$foraging_distance, df,
            subplot_coords = c(0.8, 2.2, -5, -2)
          )
        )
      )
    } else {
      ret <- list(
        site_name = list(
          results_tibble,
          make_full_plot(subdat$foraging_distance, df)
        )
      )
    }
    return(ret)
  }
)
```


```{r}

plots <- plots_data %>%
  purrr::map(
    ~ {
      site <- unique(.x[[1]][[1]]$site)
      ret <- list(.x[[1]][[2]])
      names(ret) <- site
      return(ret)
    }
  )

all_data <- plots_data %>%
  purrr::map(
    ~ {
      .x[[1]][[1]]
    }
  ) %>%
  bind_rows()

aic_plot <- all_data %>%
  group_by(site) %>%
  slice(which.min(AIC)) %>%
  select(data_name) %>%
  group_by(data_name) %>%
  summarise(lowest_AIC = n()) %>%
  ggplot(aes(x = data_name, y = lowest_AIC)) +
  geom_bar(stat = "identity") +
  labs(x = "Model", y = "Number of lowest AIC sites") +
  scale_y_continuous(breaks = seq(0, 20, by = 2))

ggsave(
  plot = aic_plot,
  filename = "analysis/figures/AIC_plot.png",
  width = 86,
  height = 90,
  units = "mm",
  dpi = 400
)

ks_plot_dist <- all_data %>%
  ggplot(aes(x = ks_p)) +
  geom_histogram(bins = 10, binwidth = 0.1, col = "white") +
  geom_vline(xintercept = 0.05, color = "red", linetype = "dashed") +
  scale_y_continuous(breaks = seq(0, 12, by = 2)) +
  labs(x = "KS P value") +
  facet_wrap(~data_name, nrow = 3)

stats_plot <- plot_grid(
  aic_plot,
  ks_plot_dist,
  ncol = 2,
  labels = c("A", "B")
)
```


Model fitting results to real data
```{r}

ggsave(
  plot = plots[[20]][[1]],
  filename = "analysis/figures/zsl_plot.png",
  width = 86,
  height = 90,
  units = "mm",
  dpi = 400
)

plots[[20]][[1]]

ggsave(
  plot = stats_plot,
  filename = "analysis/figures/model_fits.png",
  width = 178,
  height = 200,
  units = "mm",
  dpi = 400
)

stats_plot

ggsave(
  plot = ks_plot_dist,
  filename = "analysis/figures/sites_ks.png",
  width = 86,
  height = 180,
  units = "mm",
  dpi = 400
)
```


### Map plots

```{r}

library(ggplot2)
library(ggsn)
library(sf)

full_data_path <- "analysis/data/FullHBForagingData.csv"
data_raw <- tibble(read.csv(full_data_path))

map_data <- data_raw %>%
  select(
    site, lat, lon
  ) %>%
  distinct()

map_data <- all_data %>%
  group_by(site) %>%
  slice(which.min(AIC)) %>%
  select(site, data_name) %>%
  left_join(map_data, on = "site")

locations <- st_as_sf(
  map_data,
  coords = c("lon", "lat"), crs = 4326
)

base <- st_read("analysis/shapefiles/english_region_region.shp")

# location of sites box
locations
selected_sites <- filter(locations, site %in% c("STU", "ZSL"))
points_area <- st_as_sfc(st_bbox(locations))

# cropped
croped_data <- st_crop(
  base,
  xmin = 450000,
  xmax = 650000,
  ymin = 91000,
  ymax = 230000
)

zoom_plt <- ggplot() +
  geom_sf(data = croped_data, fill = "#e5f5f9") +
  geom_sf(data = locations, aes(colour = data_name), size = 1) +
  # geom_sf_text(
  #   data = selected_sites,
  #   aes(label = site, family = "URWHelvetica"),
  #   size = 2.5,
  #   nudge_x = -5000,
  #   nudge_y = 3000
  # ) +
  theme_void() +
  theme(
    text = element_text(family = "URWHelvetica", size = 8),
    legend.position = "bottom"
  )

plt <- ggplot() +
  geom_sf(data = base, fill = "white") +
  geom_sf(data = points_area, fill = NA, colour = "blue") +
  theme_void() +
  theme(
    text = element_text(family = "URWHelvetica", size = 8),
    legend.position = "none"
  )

merge_plot <- ggdraw() +
  draw_plot(ggplotGrob(zoom_plt)) +
  draw_plot(plt, x = 0.03, y = 0.3, width = 0.35, height = 0.35)

merge_plot

ggsave(
  plot = merge_plot,
  file = "analysis/figures/map_aic.png",
  width = 86,
  height = 90,
  units = "mm",
  dpi = 400
)

ggsave(
  plot = plots[[20]][[1]],
  file = "analysis/figures/ZSL.png",
  width = 86,
  height = 90,
  units = "mm",
  dpi = 400
)

ggsave(
  plot = plots[[17]][[1]],
  file = "analysis/figures/STU.png",
  width = 86,
  height = 90,
  units = "mm",
  dpi = 400
)
```
