# Analysis of the proportion of scouts across environmental gradients
## Joseph Palmer
---

```{r, include = FALSE}
devtools::load_all()

knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "man/figures/README-",
  out.width = "100%"
)
library(ggplot2)
theme_set(
  theme_classic() +
    theme(
      text = element_text(family = "URWHelvetica", size = 8)
    )
)
library(cowplot)
library(dplyr)
library(tibble)
source("analysis/fit_data.R")
```


```{r}

calc_p_likelihood <- function(sitedata, ls, ln, qn, a) {
  p_vals <- seq(0, 1, 0.001)
  result <- purrr::map_dbl(
    p_vals,
    ~ {
      loglike_model_all(sitedata, .x, ls, ln, qn, a)
    }
  )
  return(tibble::tibble(p = p_vals, loglike = result, likelihood = exp(result)))
}

```


```{r}

# load analysis results
path <- "analysis/results_version1"
data <- get_data()
sites <- purrr::map_chr(
  list.files(path),
  ~ {
    return(gsub(".rds", "", .x))
  }
)

# read analysis results into a single dataframe
model_results <- purrr::map(
    sites,
    ~ {
      subdat <- data %>% dplyr::filter(.data$site == .x)
      df <- readRDS(paste0(path, "/", .x, ".rds"))[-3]
      results_tibble <- make_results_tibble(df)
      results_tibble$site = .x
      return(results_tibble)
    }
  ) %>%
  bind_rows() %>%
  filter(data_name == "all")

estimated_p_likelihoods <- purrr::map(
  unique(data$site),
  ~ {
    params <- model_results %>%
      filter(site == .x) %>%
      select(ls, ln, qn, a)
    df <- data %>%
      filter(site == .x)
    calc_p_likelihood(
      as.vector(df$foraging_distance),
      params[["ls"]],
      params[["ln"]],
      params[["qn"]],
      params[["a"]]
    )
  }
)

names(estimated_p_likelihoods) <- unique(foraging_distances_by_site$site)

```


```{r}

p_plots <- purrr::map(
  names(estimated_p_likelihoods),
  ~ {
    estimated_p_likelihoods[[.x]] %>%
      gather("measurement", "value", -p) %>%
      ggplot(aes(x = p, y = value)) +
        geom_point() +
        geom_vline(
          xintercept = subset(model_results, site == .x)[["p"]],
          colour = "red"
        ) +
        facet_wrap(~measurement, scale = "free_y")
  }
)

names(p_plots) <- names(estimated_p_likelihoods)

master_plot <- plot_grid(
  plotlist = p_plots,
  ncol = 1,
  labels = names(p_plots)
)

ggsave("p_likelihood_space.png", height = 49)

```


```{r}
# some checks

usesite = "BEL"

sitedata <- data %>%
  filter(site == usesite)

x <- sitedata$foraging_distance

params <- model_results %>%
  filter(site == usesite) %>%
  select(p, ls, ln, qn, a)

loglike_model_all(
  x, params[["p"]],
  params[["ls"]], params[["ln"]],
  params[["qn"]], params[["a"]]
)





```
