# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Model function for scouts
#'
#' @param x double Foraging distance
#' @param m double Minimum foraging distance
#' @param p double Proportion of scouts (0<=p<=1)
#' @param ls double Scout rate
#' @param qn double Quality
#' @param a double alpha value
#' @export
scout_dist <- function(x, m, p, ls, qn, a) {
  .Call("_wagglefit_scout_dist", PACKAGE = "wagglefit", x, m, p, ls, qn, a)
}

#' Model function for recruits
#'
#' @param ln double Recruit rate
#' @inheritParams scout_dist
#' @export
recruit_dist <- function(x, m, p, ln, qn, a) {
  .Call("_wagglefit_recruit_dist", PACKAGE = "wagglefit", x, m, p, ln, qn, a)
}

#' Log-likelihood function for scout and recruit superposition
#'
#' @param x double* Pointer to array of foraging distances
#' @param x_size int Number of foraging distances
#' @inheritParams scout_dist
#' @inheritParams recruit_dist
#' @export
loglike_model_all <- function(x, x_size, p, ls, ln, qn, a) {
  .Call("_wagglefit_loglike_model_all", PACKAGE = "wagglefit", x, x_size, p, ls, ln, qn, a)
}

#' Log-likelihood function for scouts
#'
#' @inheritParams loglike_model_all
#' @export
loglike_model_scout <- function(x, x_size, ls, qn, a) {
  .Call("_wagglefit_loglike_model_scout", PACKAGE = "wagglefit", x, x_size, ls, qn, a)
}

#' Log-likelihood function for recruits
#'
#' @inheritParams loglike_model_all
#' @export
loglike_model_recruit <- function(x, x_size, ln, qn, a) {
  .Call("_wagglefit_loglike_model_recruit", PACKAGE = "wagglefit", x, x_size, ln, qn, a)
}

#' Multiply a number by two
#'
#' @param x A single integer.
#' @export
times_two <- function(x) {
  .Call("_wagglefit_times_two", PACKAGE = "wagglefit", x)
}
