# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Alter a NumericVector inplace
#'
#' @param x NumericArray
#' @export
alter_in_place <- function(x) {
  invisible(.Call("_wagglefit_alter_in_place", PACKAGE = "wagglefit", x))
}

#' Optimize function for scout and recruit superposition
#'
#' @param n unsigned, record parameter required for nlopt
#' @param NumericVector, array or parameter estimates to run the model with
#' @param grad double*, gradient value (unused but required as positional)
#' @param x NumericVector, The data to load fit to
NULL

#' Model function for scouts
#'
#' @param x double Foraging distance
#' @param m double Minimum foraging distance
#' @param p double Proportion of scouts (0<=p<=1)
#' @param ls double Scout rate
#' @param qn double Quality
#' @param a double alpha value
#' @export
scout_dist <- function(x, m, p, ls, qn, a) {
  .Call("_wagglefit_scout_dist", PACKAGE = "wagglefit", x, m, p, ls, qn, a)
}

#' Model function for recruits
#'
#' @param ln double Recruit rate
#' @inheritParams scout_dist
#' @export
recruit_dist <- function(x, m, p, ln, qn, a) {
  .Call("_wagglefit_recruit_dist", PACKAGE = "wagglefit", x, m, p, ln, qn, a)
}

#' Log-likelihood function for scout and recruit superposition
#'
#' @param x double* Pointer to array of foraging distances
#' @inheritParams scout_dist
#' @inheritParams recruit_dist
#' @export
loglike_model_all <- function(x, p, ls, ln, qn, a) {
  .Call("_wagglefit_loglike_model_all", PACKAGE = "wagglefit", x, p, ls, ln, qn, a)
}

#' Log-likelihood function for scouts
#'
#' @inheritParams loglike_model_all
#' @export
loglike_model_scout <- function(x, ls, qn, a) {
  .Call("_wagglefit_loglike_model_scout", PACKAGE = "wagglefit", x, ls, qn, a)
}

#' Log-likelihood function for recruits
#'
#' @inheritParams loglike_model_all
#' @export
loglike_model_recruit <- function(x, ln, qn, a) {
  .Call("_wagglefit_loglike_model_recruit", PACKAGE = "wagglefit", x, ln, qn, a)
}

#' Optimize function for scout and recruit superposition
#'
#' @inheritParams objective_model_all
#' @param lb NumericVector, array of lower bounds for each paramater
#' @param ub NumericVector, array of upper bounds for each parameter
#' @export
optimize_all <- function(x, params, lb, ub) {
  .Call("_wagglefit_optimize_all", PACKAGE = "wagglefit", x, params, lb, ub)
}
